// ── THE REFERENCE LINT'S OWN BLOCK-TEST AND ALLOW-TEST ────────────────────
//
// §15.2's bar, applied to the citation lint: the pure function in citations.ts
// is run against a checked-in VIOLATING corpus it must reject class by class,
// and a COMPLIANT corpus it must pass in silence. Every rejection below is
// asserted by its own named case against its own specific message — never
// "problems is non-empty" — so weakening one predicate, or deleting one rule,
// goes red on its own and cannot hide behind the other three.
//
// The corpus files carry a `path` chosen HERE rather than their location on
// disk: the function is pure and keys two of its rules on the root a file sits
// in, so the block-test hands it the roots it needs to exercise. The files
// themselves live under test/laws/fixtures/citations/, which tsconfig and biome
// exclude exactly as they exclude test/gate/fixtures.

import { readdirSync, readFileSync, statSync } from "node:fs";
import { dirname, extname, join } from "node:path";
import { describe, expect, it } from "vitest";
import { CHECKS } from "../../eslint.config.js";
import {
  BARE,
  bookSections,
  CID,
  CODE,
  COMMENT,
  type CorpusFile,
  citationProblems,
  DATA,
  LAW,
  MARKED,
  PROSE,
  RETIRED,
  ROOT_KEYS,
} from "./citations";

const HERE = dirname(new URL(import.meta.url).pathname);
const REPO = join(HERE, "..", "..", "..", "..");

/** THE SCOPE, PINNED. Narrowing any of these is a diff a reviewer sees. */
const ROOTS = ["examples", "wiki", ".github"] as const;
const EXTRA = ["laws.toml", "README.md"] as const;
const SKIPPED = [
  ".git",
  ".gradle",
  "build",
  "node_modules",
  ".work",
  // the workspace wall's declaration output — generated by `npm run
  // typecheck:wall`, git-ignored, and `.d.ts`, which `extname` reads as `.ts`.
  // Counting it would let a rebuild move a pinned census. scripts/wall.mjs
  // sweeps it on every run; this is the census's own guard against a stale one.
  ".tsbuild",
  "package-lock.json",
  "gradle-wrapper.properties",
  "gradlew",
  "gradlew.bat",
] as const;
/** The ONE path-scoped exclusion: the reference lint's own source and corpora
 *  necessarily spell the retired namespace they deny, so scanning them would
 *  make the checker deny itself. Pinned as a literal for exactly that reason. */
const SKIPPED_PATHS = ["examples/typescript/test/laws"] as const;
const EXTENSIONS = [
  ".ts",
  ".kt",
  ".kts",
  ".js",
  ".json",
  ".yml",
  ".yaml",
  ".md",
  ".html",
  ".toml",
] as const;

function walk(dir: string, out: string[]): string[] {
  for (const entry of readdirSync(dir)) {
    if ((SKIPPED as readonly string[]).includes(entry)) continue;
    const full = join(dir, entry);
    const rel = full.slice(REPO.length + 1);
    if (SKIPPED_PATHS.some((skip) => rel === skip || rel.startsWith(`${skip}/`))) continue;
    if (statSync(full).isDirectory()) walk(full, out);
    else if ((EXTENSIONS as readonly string[]).includes(extname(entry))) out.push(full);
  }
  return out;
}

const liveCorpus: CorpusFile[] = [
  ...ROOTS.flatMap((root) => walk(join(REPO, root), [])),
  ...EXTRA.map((name) => join(REPO, name)),
].map((full) => ({ path: full.slice(REPO.length + 1), text: readFileSync(full, "utf8") }));

const sections = bookSections(readFileSync(join(REPO, "wiki", "index.html"), "utf8"));
const lawIds = new Set(
  [...readFileSync(join(REPO, "laws.toml"), "utf8").matchAll(/^id = "(G\d+)"$/gm)].map(
    (m) => m[1] as string,
  ),
);

const live = citationProblems(liveCorpus, sections, lawIds);

/** Measured on the landed tree and pinned EXACTLY, the roster-pin idiom: any
 *  movement — up or down — is a deliberate one-line diff. A floor over a
 *  growable scalar is purchasable (adversarial review bought a 520-floor with
 *  one junk file of one-G-token-per-line); an equality is not, because
 *  inflation is as red as deletion. PER ROOT, so headroom bought in one root
 *  cannot fund deletions in another. */
const RESOLVABLE_PIN: Record<string, number> = {
  // the Kotlin port carries the heavier banner-comment idiom, so it cites most
  // +1 (529 -> 530): C1's banner in `gate/Rules.kt` grew from one line to five
  // to carry the canonical dependency-rule sentence verbatim (D7). It cited
  // its two section-and-law citations on one line before and on two lines
  // now — one credit became two, with no citation added or removed.
  // +1 (530 -> 531): `Replay.stateAtStep`'s doc comment cites §14.1, the section
  // whose own equation the member is named after. One line, one new citation.
  // +18 (531 -> 549): D20's snapshot half of `spine/replay` — the KDoc banners
  // on Snapshot/RecordMark/Recovery.tailFrom/refoldFrom and their ReplayTest
  // cases all cite §14.1's tagging rule and §14.6. Measured per file by this
  // module's own census, no citation removed.
  // +17 (549 -> 566): D21's schemaVersion landing — StepRecord/StepRecordV1
  // envelope KDoc, the TriageUpcast banner and the 14.7 replay-over-old-log
  // cases all cite §14.7's envelope rule. No citation removed.
  // +101 (566 -> 667): the Kotlin port becomes ADR-001 §3's module DAG. The
  // RELOCATION is citation-neutral (every spine and contract file moved with its banner
  // intact; measured per file, the moves cancel exactly), so all 101 are NEW build code
  // and the comments the split forced:
  //   +32 build-logic/ — the five convention plugins plus AdrDag.kt, where §3's
  //        dependency law, §4's two-owner IO conjunction and the measured allow-sets are
  //        written down (14 in AdrDag alone).
  //   +47 the fourteen module build scripts — :spine 2, :app 3, six blocks 2 each, six
  //        adapter leaves 5 each. Each states which edges its plugin permits, and each
  //        block pair says which §9 stage brings its files, so a DECLARED-but-empty
  //        module cannot be read as an abandoned one.
  //   +12 settings.gradle.kts 4 (the module set, the implicit :block container, the
  //        directory law) and the root build.gradle.kts 8 (what the root project now is
  //        — the gate's home plus the not-yet-migrated source — and why detekt's source
  //        set is derived from the module roots).
  //   +6  blocks/<x>/Contract.kt: triage +1, artifact +1, inbox +4 — the nested payload
  //        type's justification, why the sealed rule forces it into the transport root
  //        and why NOT into adr.spine.pure. Inbox's +4 carries the DropReason KDoc that
  //        moved here from Slice.kt (the -2 below).
  //   +4  gate/GateTest.kt 2 and gate/Tree.kt 2 — the N-root normalisation contract and
  //        the two new fail-closed tests.
  //   +0  blocks/{triage,artifact}/Slice.kt +1 each, blocks/inbox/Slice.kt -2.
  // 32 + 47 + 12 + 6 + 4 + 0 = 101.
  // Nothing was deleted: the id-and-section set present before is a subset of after.
  // +2 (667 -> 669): the orchestrator's adjudicated role-plugin wall in
  // settings.gradle.kts — its rationale comment cites ADR-001 §3/§4, the law
  // it hosts unconditionally after review proved the in-plugin roster circular.
  // +2 (669 -> 671), MEASURED per file by this module's own census with the
  // handler split applied, not derived by arithmetic:
  //   +1 spine/pure/Seams.kt — the two new effect seams, citing ADR-001 §5's rule
  //      that the effect CASES stay sealed while the handlers do not.
  //   +1 app/Wire.kt — net: it LOST the four sub-union branches and GAINED the dated
  //      receipt naming the three prose sites this landing falsifies.
  //   +1 blocks/analysis/Register.kt — 14.2's effect-descriptor note, which moved out
  //      of app/Wire.kt with the branch it belonged to.
  //   -1 build.gradle.kts — the must-fail harness's per-fixture claim is a parameter
  //      now, so one hard-coded sentence became two call-site strings.
  // Nothing was deleted from the id-and-section SET: before is a subset of after.
  // +13 (671 -> 684): the admission rule and the two new checks. §- and G-citing
  // comment lines on `Attributed`/`Admission` in spine/pure/SpineSlice.kt, the class
  // marker in spine/pure/Effect.kt, the two re-derivation loops and the digest-walk
  // exemption in spine/replay/Replay.kt, the four block contracts that classify their
  // leaf, C16's and C17's banners in test/gate/Rules.kt, and the two konsist fixture
  // pairs. Every one cites a book section or a G-id; `docs/DECISIONS.md:85` is a PATH
  // and is not a citation.
  "examples/kotlin": 684,
  // a third of the TS files are gate fixture trees that cite far less than
  // the source they stand for
  // +1 (408 -> 409): `stateAtStep`'s doc comment in spine/replay/replay.ts cites
  // §14.1 on the same grounds. No citation was removed in either port.
  // +16 (409 -> 425): the same D20 landing spelled in TS — replay.ts snapshot
  // section + replay.test.ts snapshot describe block, all citing §14.1/§14.6.
  // +1 (425 -> 426): the orchestrator's adjudicated hardening of that landing —
  // the now-half refusal test's comment cites the mutation review proved.
  // +15 (426 -> 441): D21 spelled in TS — step-record envelope banners, the
  // upcaster, record-shape.test.ts and the 14.7 replay cases, all citing §14.7.
  // +1 (441 -> 442): the workspace wall. ONE line, in gate.test.ts's new
  // wall-totality describe, citing §15.2 for the reason the enforcement
  // mechanism gets a denying check of its own. Nothing else the wall added cites
  // anything: the twenty new files are eight package manifests, eight package
  // tsconfigs, a base config, a solution file, the wall's invocation script and
  // the vitest config. No citation was removed — the four block tests that moved
  // into their packages carry the same citations at their new paths.
  // +7 (442 -> 449), the same landing in TS, MEASURED per file:
  //   +3 src/app/wire.ts — the sink banner became a dispatcher banner plus the dated
  //      receipt, which names wiki §6.8, wiki §16 and ADR-001 §1.3 Q1 on three lines
  //      as the sites this landing falsifies, and states the MEASURED replacement set
  //      rather than a bare zero.
  //   +1 src/spine/boundary/in-memory.ts — the dispatcher sink, citing G9's replay
  //      contract.
  //   +1 src/blocks/analysis/register.ts — the publish handler, carrying 14.2 with it
  //      out of app/wire.ts.
  //   +1 eslint.config.js — the `.work/**` ignore's reason, citing G12 for whose
  //      harness the scratch copy belongs to.
  //   +1 vitest.config.ts — the same scratch copy, from the walk that EXECUTES what it
  //      finds; it cites G12 for the same reason.
  // src/spine/pure/effect.ts and the four block `handlers` tables add no citation
  // line, so they are absent above by measurement rather than by omission.
  // +15 (449 -> 464): the same landing on this port. §-citing comment lines in
  // spine/pure/effect.ts (the rule, the class marker and the residue note),
  // spine/replay/replay.ts, app/assemble.ts, the four block contracts, eslint.config.js
  // (C16 and C7's FORM half), test/gate/c17.ts, test/gate/c17.test.ts and the two
  // eslint fixture pairs.
  "examples/typescript": 464,
  // nearly all of it the book's own G-table and cross-references. 137 before
  // §15's inversion merged the separate layer table INTO the invariant table:
  // its sixteen rows were sixteen separately-credited lines and are now the
  // fourth cell of the sixteen rows already counted, so the same sixteen
  // citations sit on half as many lines. No citation was deleted — the G-ids
  // present before and absent after are the empty set.
  wiki: 121,
};
const FILE_PIN: Record<string, number> = {
  // +22 (156 -> 178): ADR-001 §3's DAG adds build code and nothing else — eight files
  // under build-logic/ (its own settings + build script, AdrDag.kt and the five
  // convention plugins) and fourteen module build scripts, one per declared module.
  // No source file was added or deleted: the 43 that entered `:spine` were relocated.
  // +4 (178 -> 182): the effect-kind must-fail fixture PAIR, TWO files per polarity.
  // `EffectKind.kt` holds the consumer; `Root.kt` is a stand-in composition root in
  // the post-split idiom, and it is there because a single-file fixture directory made
  // the harness's "and nowhere else" guard empty by construction — a wall that cannot
  // fire. No source file was added: the block performers ride the Register.kt files
  // that already existed.
  // +2 (182 -> 184): the exhaustive pair's out-of-block Root.kt stand-ins,
  // shipped in both polarities so the "and nowhere else" guard is a real
  // measurement (review proved it empty by construction).
  // +11 (184 -> 195): the admission probe (`src/test/kotlin/adr/spine/AdmissionTest.kt`)
  // and TWO fixture pairs — C16 one file per polarity, C17 five violating (one per
  // spelling plus the contract the derivation reads) and three compliant. No source
  // file was added: the rule rides `spine/pure/SpineSlice.kt`, which already declared
  // the fold contract it reads, so neither the 37-file spine roster nor the 49-file
  // blocks/app roster moves.
  "examples/kotlin": 195,
  // +19 (163 -> 182): the workspace wall, which is nineteen COUNTED non-source
  // files and not one line of new prose. Eight `package.json` and eight
  // `tsconfig.json` (the spine, the six blocks, the composition root), plus
  // `tsconfig.base.json` (the options the eight inherit), `tsconfig.wall.json`
  // (the solution file the wall builds) and `test/support/stamp.ts` (the one
  // place a test mints a Signature, so that co-locating the block tests did not
  // put a constructor binding inside a block folder). The four block tests MOVED
  // into their packages, which is why this is +19 and not +23; `scripts/wall.mjs`
  // is UNCOUNTED because `.mjs` is absent from EXTENSIONS above, which is why the
  // wall's invocation is spelled `.mjs`.
  // +1 (182 -> 183): one new gate fixture, `violating/C1/.../triage/adapter.ts`
  // — the red half of the narrowed `EXTERNAL` cell, which is the regression the
  // wall would otherwise have introduced (an adapter's licence to hold a client
  // library becoming a licence to hold `spine/boundary`).
  // +1 (183 -> 184): `vitest.config.ts`, which excludes `.tsbuild` from the one
  // walk that EXECUTES what it finds rather than counting it.
  // +1 (184 -> 185): the novel-effect-kind patch fixture, the second fixture the
  // exhaustiveness harness drives. No source file was added: the block handler tables
  // ride the register.ts files that already existed, and the harness's scratch copy is
  // named `.work`, which the walk above already skips by entry name.
  // +15 (185 -> 200): the admission probe (`test/spine/admission.test.ts`), C17's
  // checker and its own test (`test/gate/c17.ts`, `test/gate/c17.test.ts`), C16's
  // fixture PAIR, C17's fixture pair (five violating, three compliant), and the pair
  // for C7's newly-closed computed-key hole — a widening that gets its own pair rather
  // than riding C7's existing files, so it cannot ship vacuous. The count-coherence
  // check is NOT among them: `test/laws` is this census's one path-scoped exclusion.
  // No source file was added: `admit` rides `src/spine/pure/effect.ts`, which already
  // declared `EffectBase`, so the 36-file spine roster does not move.
  "examples/typescript": 200,
  wiki: 10,
};

describe("citations resolve — one public namespace", () => {
  it("scans the pinned scope, and the scope cannot quietly shrink", () => {
    expect([...ROOTS]).toEqual(["examples", "wiki", ".github"]);
    expect([...EXTRA]).toEqual(["laws.toml", "README.md"]);
    expect([...SKIPPED_PATHS]).toEqual(["examples/typescript/test/laws"]);
    expect([...SKIPPED]).toEqual([
      ".git",
      ".gradle",
      "build",
      "node_modules",
      ".work",
      ".tsbuild",
      "package-lock.json",
      "gradle-wrapper.properties",
      "gradlew",
      "gradlew.bat",
    ]);
    expect([...EXTENSIONS]).toEqual([
      ".ts",
      ".kt",
      ".kts",
      ".js",
      ".json",
      ".yml",
      ".yaml",
      ".md",
      ".html",
      ".toml",
    ]);
    expect(liveCorpus.length).toBeGreaterThanOrEqual(330);
  });

  it("PINS THE PREDICATES — a weakened denial is a visible diff, not a silence", () => {
    expect(RETIRED.source).toBe("\\b[FALD]\\d+\\b");
    expect(MARKED.source).toBe("§\\s?(\\d{1,3}(?:\\.\\d+)*)");
    expect(BARE.source).toBe("(?<![\\w.§])(\\d{1,2}\\.\\d{1,2}(?:\\.\\d+)?)(?!\\d)");
    expect(LAW.source).toBe("\\bG\\d+\\b");
    expect(CID.source).toBe("\\bC\\d{1,2}\\b");
    expect(COMMENT.source).toBe("^\\s*(\\/\\/|\\/\\*|\\*|#)");
    expect([...CODE]).toEqual([".ts", ".kt", ".kts", ".js", ".yml", ".yaml"]);
    expect([...DATA]).toEqual([".json", ".toml"]);
    expect([...PROSE]).toEqual([".md", ".html"]);
    expect([...ROOT_KEYS]).toEqual(["examples/typescript", "examples/kotlin", "wiki", ".github"]);
    // The law-id set is DERIVED from the registry, never a hard-coded range.
    expect(lawIds.size).toBe(16);
    expect(lawIds.has("G17")).toBe(false);
  });

  it("THE CHECK-ID NAMESPACE COVERS THE WHOLE LIVE ROSTER — derived, not a range", () => {
    // The hole this closes, measured: `\bC(?:1[0-5]|[1-9])\b` could not match
    // "C16" — the `1[0-5]` alternative fails on the `6` and the `[1-9]`
    // alternative leaves `\b` asserting between two word characters — so the
    // FIRST id the next landing mints fell straight out of D30's denial while
    // C15, one digit away, was caught. The bound is gone; this is the assertion
    // that keeps the pattern bound to the roster instead, and it is DERIVED from
    // the shipped config rather than re-listed here.
    expect(CHECKS.length).toBeGreaterThan(15);
    for (const check of CHECKS) {
      expect(
        [...`the gate ships ${check.id} today`.matchAll(CID)].map((m) => m[0]),
        check.id,
      ).toEqual([check.id]);
    }
    // …and it is not a rule that matches anything: an ordinary word is not an id.
    expect([..."the Cn roster and G16".matchAll(CID)]).toEqual([]);
  });

  it("cites no retired review id anywhere", () => {
    expect(live.retired.map((h) => `${h.where}  ${h.text}`)).toEqual([]);
  });

  it("cites no section the book does not have", () => {
    expect(live.phantomSection.map((h) => `${h.where}  ${h.text}`)).toEqual([]);
  });

  it("cites no law the registry does not carry", () => {
    expect(live.phantomLaw.map((h) => `${h.where}  ${h.text}`)).toEqual([]);
  });

  it("cites no check id as book authority", () => {
    expect(live.bookCid.map((h) => `${h.where}  ${h.text}`)).toEqual([]);
  });

  it("keeps EXACTLY the RESOLVABLE citations the sweep left, PER ROOT", () => {
    // The pin that makes both attacks fail: "delete the comment" drops the
    // count (retiring an id must PRODUCE a public citation, not remove a
    // sentence), and "inflate with a junk citation file" RAISES it — either
    // direction is a red diff a reviewer sees. Editing citations legitimately
    // means updating this pin in the same change, with one line of reasoning.
    for (const [root, pin] of Object.entries(RESOLVABLE_PIN)) {
      expect(live.resolvable[root] ?? 0, `resolvable[${root}]`).toBe(pin);
    }
    for (const [root, pin] of Object.entries(FILE_PIN)) {
      expect(live.files[root] ?? 0, `files[${root}]`).toBe(pin);
    }
  });

  it("the book's own section set parsed — an empty set would pass everything", () => {
    expect(sections.size).toBeGreaterThanOrEqual(100);
    expect(sections.has("15.3")).toBe(true);
    expect(sections.has("14.1.1")).toBe(true);
    expect(sections.has("1.5")).toBe(false);
  });
});

// ── the lint's own BLOCK-TEST and ALLOW-TEST ──────────────────────────────
const corpusFile = (half: string, name: string, path: string): CorpusFile => ({
  path,
  text: readFileSync(join(HERE, "fixtures", "citations", half, name), "utf8"),
});

const violating = citationProblems(
  [
    corpusFile("violating", "code.ts", "examples/typescript/src/violating.ts"),
    corpusFile("violating", "prose.html", "wiki/violating.html"),
    corpusFile("violating", "data.json", "examples/typescript/violating.json"),
  ],
  sections,
  lawIds,
);
const said = (hits: readonly { where: string; text: string }[]) =>
  hits.map((h) => `${h.where}  ${h.text}`).join("\n");

describe("the reference lint DENIES a violating corpus", () => {
  it("REJECTS a retired F id", () => {
    expect(said(violating.retired)).toContain("F9");
  });

  it("REJECTS a retired A id", () => {
    expect(said(violating.retired)).toContain("A4");
  });

  it("REJECTS a retired L id", () => {
    expect(said(violating.retired)).toContain("L3");
  });

  it("REJECTS a retired D id — the COLLIDED namespace", () => {
    // The one that matters most: the same spelling names an unrelated entry in
    // the ratified record, so narrowing the class to [FAL] must go red here.
    expect(said(violating.retired)).toContain("D4");
  });

  it("REJECTS a §-marked section the book does not have", () => {
    expect(said(violating.phantomSection)).toContain("§1.5");
  });

  it("REJECTS a bare section number on a comment line", () => {
    expect(said(violating.phantomSection)).toContain(
      "examples/typescript/src/violating.ts:10  §8.6",
    );
  });

  it("REJECTS a bare section number in a VALUE, where no comment marker is", () => {
    expect(said(violating.phantomSection)).toContain(
      "examples/typescript/src/violating.ts:13  §8.6",
    );
  });

  it("REJECTS a bare section number in a data file, which has no comments at all", () => {
    expect(said(violating.phantomSection)).toContain("examples/typescript/violating.json:2  §8.6");
  });

  it("REJECTS a bare head OUTSIDE the book's range instead of dropping it", () => {
    expect(said(violating.phantomSection)).toContain("§99.9");
  });

  it("REJECTS a G-id the registry does not carry", () => {
    expect(said(violating.phantomLaw)).toContain("G17");
  });

  it("REJECTS a check id cited as authority in the book", () => {
    expect(said(violating.bookCid)).toContain("wiki/violating.html:1  C7");
  });
});

describe("the reference lint ALLOWS a compliant corpus", () => {
  const compliant = citationProblems(
    [
      corpusFile("compliant", "code.ts", "examples/typescript/src/compliant.ts"),
      corpusFile("compliant", "prose.md", "examples/typescript/COMPLIANT.md"),
      corpusFile("compliant", "data.json", "examples/typescript/compliant.json"),
    ],
    sections,
    lawIds,
  );

  it("passes every spelling the sweep introduced, and every near-miss", () => {
    // `G9, 14.1`, `§15.4`, `14.1.1`, `12.4`, `6.8`, a roster row naming C4, a
    // `[C2]` message tag, `node >=14.17`, `Apache-2.0` and `2.5.5`.
    expect(said(compliant.retired)).toBe("");
    expect(said(compliant.phantomSection)).toBe("");
    expect(said(compliant.phantomLaw)).toBe("");
    expect(said(compliant.bookCid)).toBe("");
  });
});
