// ── THE REFERENCE LINT'S OWN BLOCK-TEST AND ALLOW-TEST ────────────────────
//
// §15.2's bar, applied to the citation lint: the pure function in citations.ts
// is run against a checked-in VIOLATING corpus it must reject class by class,
// and a COMPLIANT corpus it must pass in silence. Every rejection below is
// asserted by its own named case against its own specific message — never
// "problems is non-empty" — so weakening one predicate, or deleting one rule,
// goes red on its own and cannot hide behind the other three.
//
// The corpus files carry a `path` chosen HERE rather than their location on
// disk: the function is pure and keys two of its rules on the root a file sits
// in, so the block-test hands it the roots it needs to exercise. The files
// themselves live under test/laws/fixtures/citations/, which tsconfig and biome
// exclude exactly as they exclude test/gate/fixtures.
//
// TWO LINTS, TWO PAIRS. `citationProblems` judges a reference's TEXT; the second
// half of this file drives `crossRefProblems`, which judges a LINK — its href
// and its visible label, the book's other coordinate — against its own
// violating/compliant mini-book pair. Same idiom throughout: one case per denied
// class, each asserting its own located message.

import { readdirSync, readFileSync, statSync } from "node:fs";
import { dirname, extname, join } from "node:path";
import { describe, expect, it } from "vitest";
import { CHECKS } from "../../eslint.config.js";
import {
  ANCHOR,
  BARE,
  bookSections,
  CID,
  CODE,
  COMMENT,
  type CorpusFile,
  citationProblems,
  crossRefProblems,
  DATA,
  ELEMENT_ID,
  EXTERNAL,
  HEAD,
  LAW,
  LAW_CELL,
  LAW_LABEL,
  MARKED,
  NAV_LABEL,
  NUMBER_LABEL,
  PROSE,
  RETIRED,
  ROOT_KEYS,
  SECTION,
  SECTION_SIGN,
  SECTION_TAG,
  SUBHEAD,
  TAGS,
  WORDED_LABEL,
} from "./citations";

const HERE = dirname(new URL(import.meta.url).pathname);
const REPO = join(HERE, "..", "..", "..", "..");

/** THE SCOPE, PINNED. Narrowing any of these is a diff a reviewer sees. */
const ROOTS = ["examples", "wiki", ".github"] as const;
/** +2: the two root documents the release ritual owns. They are IN the corpus on
 *  purpose — a CHANGELOG outside it may spell a retired review id or a phantom
 *  section, and it is the one file a vendored copy is asked to read. `docs/` is
 *  deliberately NOT a root, which is what lets the ratified record spell its own
 *  retired ids; putting these two there would have left the deliverable ungated.
 *  `OPEN-GAPS.md` is deliberately NOT here: measured, that document spells
 *  SIXTEEN retired ids (A1, A2, A3x2, A4, A5x2, A6, F1x2, F4x3, F11, F13x2)
 *  because archiving them is what it is for, so admitting it would force either
 *  a path exemption that defeats the census or the deletion of the archive.
 *  Its counted claims are owned by the count-coherence check instead. */
const EXTRA = ["laws.toml", "README.md", "CHANGELOG.md", "RELEASE-RITUAL.md"] as const;
const SKIPPED = [
  ".git",
  ".gradle",
  "build",
  "node_modules",
  ".work",
  // the workspace wall's declaration output — generated by `npm run
  // typecheck:wall`, git-ignored, and `.d.ts`, which `extname` reads as `.ts`.
  // Counting it would let a rebuild move a pinned census. scripts/wall.mjs
  // sweeps it on every run; this is the census's own guard against a stale one.
  ".tsbuild",
  "package-lock.json",
  "gradle-wrapper.properties",
  "gradlew",
  "gradlew.bat",
] as const;
/** The ONE path-scoped exclusion: the reference lint's own source and corpora
 *  necessarily spell the retired namespace they deny, so scanning them would
 *  make the checker deny itself. Pinned as a literal for exactly that reason. */
const SKIPPED_PATHS = ["examples/typescript/test/laws"] as const;
const EXTENSIONS = [
  ".ts",
  ".kt",
  ".kts",
  ".js",
  ".json",
  ".yml",
  ".yaml",
  ".md",
  ".html",
  ".toml",
] as const;

function walk(dir: string, out: string[]): string[] {
  for (const entry of readdirSync(dir)) {
    if ((SKIPPED as readonly string[]).includes(entry)) continue;
    const full = join(dir, entry);
    const rel = full.slice(REPO.length + 1);
    if (SKIPPED_PATHS.some((skip) => rel === skip || rel.startsWith(`${skip}/`))) continue;
    if (statSync(full).isDirectory()) walk(full, out);
    else if ((EXTENSIONS as readonly string[]).includes(extname(entry))) out.push(full);
  }
  return out;
}

const liveCorpus: CorpusFile[] = [
  ...ROOTS.flatMap((root) => walk(join(REPO, root), [])),
  ...EXTRA.map((name) => join(REPO, name)),
].map((full) => ({ path: full.slice(REPO.length + 1), text: readFileSync(full, "utf8") }));

const sections = bookSections(readFileSync(join(REPO, "wiki", "index.html"), "utf8"));
const lawIds = new Set(
  [...readFileSync(join(REPO, "laws.toml"), "utf8").matchAll(/^id = "(G\d+)"$/gm)].map(
    (m) => m[1] as string,
  ),
);

const live = citationProblems(liveCorpus, sections, lawIds);

/** Measured on the landed tree and pinned EXACTLY, the roster-pin idiom: any
 *  movement — up or down — is a deliberate one-line diff. A floor over a
 *  growable scalar is purchasable (adversarial review bought a 520-floor with
 *  one junk file of one-G-token-per-line); an equality is not, because
 *  inflation is as red as deletion. PER ROOT, so headroom bought in one root
 *  cannot fund deletions in another. */
const RESOLVABLE_PIN: Record<string, number> = {
  // the Kotlin port carries the heavier banner-comment idiom, so it cites most
  // +1 (529 -> 530): C1's banner in `gate/Rules.kt` grew from one line to five
  // to carry the canonical dependency-rule sentence verbatim (D7). It cited
  // its two section-and-law citations on one line before and on two lines
  // now — one credit became two, with no citation added or removed.
  // +1 (530 -> 531): `Replay.stateAtStep`'s doc comment cites §14.1, the section
  // whose own equation the member is named after. One line, one new citation.
  // +18 (531 -> 549): D20's snapshot half of `spine/replay` — the KDoc banners
  // on Snapshot/RecordMark/Recovery.tailFrom/refoldFrom and their ReplayTest
  // cases all cite §14.1's tagging rule and §14.6. Measured per file by this
  // module's own census, no citation removed.
  // +17 (549 -> 566): D21's schemaVersion landing — StepRecord/StepRecordV1
  // envelope KDoc, the TriageUpcast banner and the 14.7 replay-over-old-log
  // cases all cite §14.7's envelope rule. No citation removed.
  // +101 (566 -> 667): the Kotlin port becomes ADR-001 §3's module DAG. The
  // RELOCATION is citation-neutral (every spine and contract file moved with its banner
  // intact; measured per file, the moves cancel exactly), so all 101 are NEW build code
  // and the comments the split forced:
  //   +32 build-logic/ — the five convention plugins plus AdrDag.kt, where §3's
  //        dependency law, §4's two-owner IO conjunction and the measured allow-sets are
  //        written down (14 in AdrDag alone).
  //   +47 the fourteen module build scripts — :spine 2, :app 3, six blocks 2 each, six
  //        adapter leaves 5 each. Each states which edges its plugin permits, and each
  //        block pair says which §9 stage brings its files, so a DECLARED-but-empty
  //        module cannot be read as an abandoned one.
  //   +12 settings.gradle.kts 4 (the module set, the implicit :block container, the
  //        directory law) and the root build.gradle.kts 8 (what the root project now is
  //        — the gate's home plus the not-yet-migrated source — and why detekt's source
  //        set is derived from the module roots).
  //   +6  blocks/<x>/Contract.kt: triage +1, artifact +1, inbox +4 — the nested payload
  //        type's justification, why the sealed rule forces it into the transport root
  //        and why NOT into adr.spine.pure. Inbox's +4 carries the DropReason KDoc that
  //        moved here from Slice.kt (the -2 below).
  //   +4  gate/GateTest.kt 2 and gate/Tree.kt 2 — the N-root normalisation contract and
  //        the two new fail-closed tests.
  //   +0  blocks/{triage,artifact}/Slice.kt +1 each, blocks/inbox/Slice.kt -2.
  // 32 + 47 + 12 + 6 + 4 + 0 = 101.
  // Nothing was deleted: the id-and-section set present before is a subset of after.
  // +2 (667 -> 669): the orchestrator's adjudicated role-plugin wall in
  // settings.gradle.kts — its rationale comment cites ADR-001 §3/§4, the law
  // it hosts unconditionally after review proved the in-plugin roster circular.
  // +2 (669 -> 671), MEASURED per file by this module's own census with the
  // handler split applied, not derived by arithmetic:
  //   +1 spine/pure/Seams.kt — the two new effect seams, citing ADR-001 §5's rule
  //      that the effect CASES stay sealed while the handlers do not.
  //   +1 app/Wire.kt — net: it LOST the four sub-union branches and GAINED the dated
  //      receipt naming the three prose sites this landing falsifies.
  //   +1 blocks/analysis/Register.kt — 14.2's effect-descriptor note, which moved out
  //      of app/Wire.kt with the branch it belonged to.
  //   -1 build.gradle.kts — the must-fail harness's per-fixture claim is a parameter
  //      now, so one hard-coded sentence became two call-site strings.
  // Nothing was deleted from the id-and-section SET: before is a subset of after.
  // +13 (671 -> 684): the admission rule and the two new checks. §- and G-citing
  // comment lines on `Attributed`/`Admission` in spine/pure/SpineSlice.kt, the class
  // marker in spine/pure/Effect.kt, the two re-derivation loops and the digest-walk
  // exemption in spine/replay/Replay.kt, the four block contracts that classify their
  // leaf, C16's and C17's banners in test/gate/Rules.kt, and the two konsist fixture
  // pairs. Every one cites a book section or a G-id; `docs/DECISIONS.md:85` is a PATH
  // and is not a citation.
  // +24 (684 -> 708): the module-ownership pin. `GateFile` keeps the module root it
  // was read from instead of discarding it; `GateTrees` gains the owed-root
  // derivation, the two violation predicates, and the rim derivation whose
  // in-checker fixture pair the new test drives; `GateTest` gains the MODULE
  // OWNERSHIP test. Measured per file by this module's own census, never derived by
  // arithmetic: gate/Tree.kt 3 -> 19, gate/GateTest.kt 13 -> 21. The new banners
  // cite the ratified sections behind the two ownership exceptions, behind the
  // module pair whose classpath ban the pin re-attaches, and behind the coordinate
  // escape it measured. Nothing was deleted: the id-and-section set present before
  // is a subset of after.
  // +4 (708 -> 712): D42's spine version marker and the module-ownership wall
  // (the path-to-module pin) each cite the decisions they hold.
  "examples/kotlin": 712,
  // a third of the TS files are gate fixture trees that cite far less than
  // the source they stand for
  // +1 (408 -> 409): `stateAtStep`'s doc comment in spine/replay/replay.ts cites
  // §14.1 on the same grounds. No citation was removed in either port.
  // +16 (409 -> 425): the same D20 landing spelled in TS — replay.ts snapshot
  // section + replay.test.ts snapshot describe block, all citing §14.1/§14.6.
  // +1 (425 -> 426): the orchestrator's adjudicated hardening of that landing —
  // the now-half refusal test's comment cites the mutation review proved.
  // +15 (426 -> 441): D21 spelled in TS — step-record envelope banners, the
  // upcaster, record-shape.test.ts and the 14.7 replay cases, all citing §14.7.
  // +1 (441 -> 442): the workspace wall. ONE line, in gate.test.ts's new
  // wall-totality describe, citing §15.2 for the reason the enforcement
  // mechanism gets a denying check of its own. Nothing else the wall added cites
  // anything: the twenty new files are eight package manifests, eight package
  // tsconfigs, a base config, a solution file, the wall's invocation script and
  // the vitest config. No citation was removed — the four block tests that moved
  // into their packages carry the same citations at their new paths.
  // +7 (442 -> 449), the same landing in TS, MEASURED per file:
  //   +3 src/app/wire.ts — the sink banner became a dispatcher banner plus the dated
  //      receipt, which names wiki §6.8, wiki §16 and ADR-001 §1.3 Q1 on three lines
  //      as the sites this landing falsifies, and states the MEASURED replacement set
  //      rather than a bare zero.
  //   +1 src/spine/boundary/in-memory.ts — the dispatcher sink, citing G9's replay
  //      contract.
  //   +1 src/blocks/analysis/register.ts — the publish handler, carrying 14.2 with it
  //      out of app/wire.ts.
  //   +1 eslint.config.js — the `.work/**` ignore's reason, citing G12 for whose
  //      harness the scratch copy belongs to.
  //   +1 vitest.config.ts — the same scratch copy, from the walk that EXECUTES what it
  //      finds; it cites G12 for the same reason.
  // src/spine/pure/effect.ts and the four block `handlers` tables add no citation
  // line, so they are absent above by measurement rather than by omission.
  // +15 (449 -> 464): the same landing on this port. §-citing comment lines in
  // spine/pure/effect.ts (the rule, the class marker and the residue note),
  // spine/replay/replay.ts, app/assemble.ts, the four block contracts, eslint.config.js
  // (C16 and C7's FORM half), test/gate/c17.ts, test/gate/c17.test.ts and the two
  // eslint fixture pairs.
  // +4 (464 -> 468): `spine/pure/version.ts`, the same marker in this port's
  // spelling and the same four citations. Measured per file; wire.ts and
  // step-record.ts moved by zero for the reason given on the Kotlin pin above.
  "examples/typescript": 468,
  // nearly all of it the book's own G-table and cross-references. 137 before
  // §15's inversion merged the separate layer table INTO the invariant table:
  // its sixteen rows were sixteen separately-credited lines and are now the
  // fourth cell of the sixteen rows already counted, so the same sixteen
  // citations sit on half as many lines. No citation was deleted — the G-ids
  // present before and absent after are the empty set.
  wiki: 121,
  // NEWLY PINNED, and the reason is this landing: `root` is where a file that
  // is in the corpus but under none of the four ROOT_KEYS lands, and until now
  // that was three files nobody counted. The release documents live there, so
  // leaving the bucket unpinned would have made "delete the migration prose" the
  // one citation edit this census cannot see — precisely the attack the per-root
  // equality exists to stop. Measured: laws.toml 22, README.md 2, CHANGELOG.md 4,
  // RELEASE-RITUAL.md 6, examples/README.md 0.
  root: 34,
  // NEWLY PINNED for the identical reason and in the same breath: `.github` was
  // a DECLARED root key with no pin, so the loop below — which iterates the PIN
  // map, never the live buckets — skipped it by construction. Measured: one
  // file, `.github/workflows/ci.yml`, citing on two lines. The assertion under
  // "EVERY LIVE BUCKET IS PINNED" is what stops that hole reopening.
  ".github": 2,
};
const FILE_PIN: Record<string, number> = {
  // +22 (156 -> 178): ADR-001 §3's DAG adds build code and nothing else — eight files
  // under build-logic/ (its own settings + build script, AdrDag.kt and the five
  // convention plugins) and fourteen module build scripts, one per declared module.
  // No source file was added or deleted: the 43 that entered `:spine` were relocated.
  // +4 (178 -> 182): the effect-kind must-fail fixture PAIR, TWO files per polarity.
  // `EffectKind.kt` holds the consumer; `Root.kt` is a stand-in composition root in
  // the post-split idiom, and it is there because a single-file fixture directory made
  // the harness's "and nowhere else" guard empty by construction — a wall that cannot
  // fire. No source file was added: the block performers ride the Register.kt files
  // that already existed.
  // +2 (182 -> 184): the exhaustive pair's out-of-block Root.kt stand-ins,
  // shipped in both polarities so the "and nowhere else" guard is a real
  // measurement (review proved it empty by construction).
  // +11 (184 -> 195): the admission probe (`src/test/kotlin/adr/spine/AdmissionTest.kt`)
  // and TWO fixture pairs — C16 one file per polarity, C17 five violating (one per
  // spelling plus the contract the derivation reads) and three compliant. No source
  // file was added: the rule rides `spine/pure/SpineSlice.kt`, which already declared
  // the fold contract it reads, so neither the 37-file spine roster nor the 49-file
  // blocks/app roster moves.
  // +1 (195 -> 196): `spine/pure/Version.kt`. One source file, the spine version
  // marker, which is why the 37-file spine roster moves to 38 in the same diff.
  "examples/kotlin": 196,
  // +19 (163 -> 182): the workspace wall, which is nineteen COUNTED non-source
  // files and not one line of new prose. Eight `package.json` and eight
  // `tsconfig.json` (the spine, the six blocks, the composition root), plus
  // `tsconfig.base.json` (the options the eight inherit), `tsconfig.wall.json`
  // (the solution file the wall builds) and `test/support/stamp.ts` (the one
  // place a test mints a Signature, so that co-locating the block tests did not
  // put a constructor binding inside a block folder). The four block tests MOVED
  // into their packages, which is why this is +19 and not +23; `scripts/wall.mjs`
  // is UNCOUNTED because `.mjs` is absent from EXTENSIONS above, which is why the
  // wall's invocation is spelled `.mjs`.
  // +1 (182 -> 183): one new gate fixture, `violating/C1/.../triage/adapter.ts`
  // — the red half of the narrowed `EXTERNAL` cell, which is the regression the
  // wall would otherwise have introduced (an adapter's licence to hold a client
  // library becoming a licence to hold `spine/boundary`).
  // +1 (183 -> 184): `vitest.config.ts`, which excludes `.tsbuild` from the one
  // walk that EXECUTES what it finds rather than counting it.
  // +1 (184 -> 185): the novel-effect-kind patch fixture, the second fixture the
  // exhaustiveness harness drives. No source file was added: the block handler tables
  // ride the register.ts files that already existed, and the harness's scratch copy is
  // named `.work`, which the walk above already skips by entry name.
  // +15 (185 -> 200): the admission probe (`test/spine/admission.test.ts`), C17's
  // checker and its own test (`test/gate/c17.ts`, `test/gate/c17.test.ts`), C16's
  // fixture PAIR, C17's fixture pair (five violating, three compliant), and the pair
  // for C7's newly-closed computed-key hole — a widening that gets its own pair rather
  // than riding C7's existing files, so it cannot ship vacuous. The count-coherence
  // check is NOT among them: `test/laws` is this census's one path-scoped exclusion.
  // No source file was added: `admit` rides `src/spine/pure/effect.ts`, which already
  // declared `EffectBase`, so the 36-file spine roster does not move.
  // +3 (200 -> 203): D1's book widening ships test/laws/edges.test.ts and the
  // three edge fixtures under test/gate/fixtures/edges/ — the build-edge rows'
  // block/allow pair.
  // +1 (203 -> 204): `src/spine/pure/version.ts`, the same marker here, moving
  // the 36-file spine roster to 37. The release check's own module, its test and
  // its eighteen fixture files are ABSENT from this count on purpose:
  // `examples/typescript/test/laws` is this census's one path-scoped exclusion.
  "examples/typescript": 204,
  wiki: 10,
  // NEWLY PINNED alongside the resolvable bucket above, and +2 in the same
  // breath: CHANGELOG.md and RELEASE-RITUAL.md join laws.toml, README.md and
  // examples/README.md. A root document deleted is now a red diff.
  root: 5,
  // NEWLY PINNED: one file in that bucket, the CI workflow.
  ".github": 1,
};

describe("citations resolve — one public namespace", () => {
  it("scans the pinned scope, and the scope cannot quietly shrink", () => {
    expect([...ROOTS]).toEqual(["examples", "wiki", ".github"]);
    expect([...EXTRA]).toEqual(["laws.toml", "README.md", "CHANGELOG.md", "RELEASE-RITUAL.md"]);
    expect([...SKIPPED_PATHS]).toEqual(["examples/typescript/test/laws"]);
    expect([...SKIPPED]).toEqual([
      ".git",
      ".gradle",
      "build",
      "node_modules",
      ".work",
      ".tsbuild",
      "package-lock.json",
      "gradle-wrapper.properties",
      "gradlew",
      "gradlew.bat",
    ]);
    expect([...EXTENSIONS]).toEqual([
      ".ts",
      ".kt",
      ".kts",
      ".js",
      ".json",
      ".yml",
      ".yaml",
      ".md",
      ".html",
      ".toml",
    ]);
    expect(liveCorpus.length).toBeGreaterThanOrEqual(330);
  });

  it("PINS THE PREDICATES — a weakened denial is a visible diff, not a silence", () => {
    expect(RETIRED.source).toBe("\\b[FALD]\\d+\\b");
    expect(MARKED.source).toBe("§\\s?(\\d{1,3}(?:\\.\\d+)*)");
    expect(BARE.source).toBe("(?<![\\w.§])(\\d{1,2}\\.\\d{1,2}(?:\\.\\d+)?)(?!\\d)");
    expect(LAW.source).toBe("\\bG\\d+\\b");
    expect(CID.source).toBe("\\bC\\d{1,2}\\b");
    expect(COMMENT.source).toBe("^\\s*(\\/\\/|\\/\\*|\\*|#)");
    expect([...CODE]).toEqual([".ts", ".kt", ".kts", ".js", ".yml", ".yaml"]);
    expect([...DATA]).toEqual([".json", ".toml"]);
    expect([...PROSE]).toEqual([".md", ".html"]);
    expect([...ROOT_KEYS]).toEqual(["examples/typescript", "examples/kotlin", "wiki", ".github"]);
    // The law-id set is DERIVED from the registry, never a hard-coded range.
    expect(lawIds.size).toBe(16);
    expect(lawIds.has("G17")).toBe(false);
  });

  it("THE CHECK-ID NAMESPACE COVERS THE WHOLE LIVE ROSTER — derived, not a range", () => {
    // The hole this closes, measured: `\bC(?:1[0-5]|[1-9])\b` could not match
    // "C16" — the `1[0-5]` alternative fails on the `6` and the `[1-9]`
    // alternative leaves `\b` asserting between two word characters — so the
    // FIRST id the next landing mints fell straight out of D30's denial while
    // C15, one digit away, was caught. The bound is gone; this is the assertion
    // that keeps the pattern bound to the roster instead, and it is DERIVED from
    // the shipped config rather than re-listed here.
    expect(CHECKS.length).toBeGreaterThan(15);
    for (const check of CHECKS) {
      expect(
        [...`the gate ships ${check.id} today`.matchAll(CID)].map((m) => m[0]),
        check.id,
      ).toEqual([check.id]);
    }
    // …and it is not a rule that matches anything: an ordinary word is not an id.
    expect([..."the Cn roster and G16".matchAll(CID)]).toEqual([]);
  });

  it("cites no retired review id anywhere", () => {
    expect(live.retired.map((h) => `${h.where}  ${h.text}`)).toEqual([]);
  });

  it("cites no section the book does not have", () => {
    expect(live.phantomSection.map((h) => `${h.where}  ${h.text}`)).toEqual([]);
  });

  it("cites no law the registry does not carry", () => {
    expect(live.phantomLaw.map((h) => `${h.where}  ${h.text}`)).toEqual([]);
  });

  it("cites no check id as book authority", () => {
    expect(live.bookCid.map((h) => `${h.where}  ${h.text}`)).toEqual([]);
  });

  it("EVERY LIVE BUCKET IS PINNED — the loop cannot skip one it has no key for", () => {
    // The hole this closes, measured: both maps held three keys while the census
    // produced five, and the assertion below iterates the PIN map rather than the
    // live buckets — so `root` and `.github` were unchecked BY CONSTRUCTION, and
    // no amount of editing files in them could turn anything red. Pinning the two
    // values is the fix for today; this is the fix for the class, because a sixth
    // bucket appearing with no pin is now red rather than silent.
    expect(Object.keys(RESOLVABLE_PIN).sort()).toEqual(Object.keys(live.resolvable).sort());
    expect(Object.keys(FILE_PIN).sort()).toEqual(Object.keys(live.files).sort());
    expect(Object.keys(FILE_PIN).length).toBe(5);
  });

  it("keeps EXACTLY the RESOLVABLE citations the sweep left, PER ROOT", () => {
    // The pin that makes both attacks fail: "delete the comment" drops the
    // count (retiring an id must PRODUCE a public citation, not remove a
    // sentence), and "inflate with a junk citation file" RAISES it — either
    // direction is a red diff a reviewer sees. Editing citations legitimately
    // means updating this pin in the same change, with one line of reasoning.
    for (const [root, pin] of Object.entries(RESOLVABLE_PIN)) {
      expect(live.resolvable[root] ?? 0, `resolvable[${root}]`).toBe(pin);
    }
    for (const [root, pin] of Object.entries(FILE_PIN)) {
      expect(live.files[root] ?? 0, `files[${root}]`).toBe(pin);
    }
  });

  it("the book's own section set parsed — an empty set would pass everything", () => {
    expect(sections.size).toBeGreaterThanOrEqual(100);
    expect(sections.has("15.3")).toBe(true);
    expect(sections.has("14.1.1")).toBe(true);
    expect(sections.has("1.5")).toBe(false);
  });
});

// ── the lint's own BLOCK-TEST and ALLOW-TEST ──────────────────────────────
const corpusFile = (half: string, name: string, path: string): CorpusFile => ({
  path,
  text: readFileSync(join(HERE, "fixtures", "citations", half, name), "utf8"),
});

const violating = citationProblems(
  [
    corpusFile("violating", "code.ts", "examples/typescript/src/violating.ts"),
    corpusFile("violating", "prose.html", "wiki/violating.html"),
    corpusFile("violating", "data.json", "examples/typescript/violating.json"),
  ],
  sections,
  lawIds,
);
const said = (hits: readonly { where: string; text: string }[]) =>
  hits.map((h) => `${h.where}  ${h.text}`).join("\n");

describe("the reference lint DENIES a violating corpus", () => {
  it("REJECTS a retired F id", () => {
    expect(said(violating.retired)).toContain("F9");
  });

  it("REJECTS a retired A id", () => {
    expect(said(violating.retired)).toContain("A4");
  });

  it("REJECTS a retired L id", () => {
    expect(said(violating.retired)).toContain("L3");
  });

  it("REJECTS a retired D id — the COLLIDED namespace", () => {
    // The one that matters most: the same spelling names an unrelated entry in
    // the ratified record, so narrowing the class to [FAL] must go red here.
    expect(said(violating.retired)).toContain("D4");
  });

  it("REJECTS a §-marked section the book does not have", () => {
    expect(said(violating.phantomSection)).toContain("§1.5");
  });

  it("REJECTS a bare section number on a comment line", () => {
    expect(said(violating.phantomSection)).toContain(
      "examples/typescript/src/violating.ts:10  §8.6",
    );
  });

  it("REJECTS a bare section number in a VALUE, where no comment marker is", () => {
    expect(said(violating.phantomSection)).toContain(
      "examples/typescript/src/violating.ts:13  §8.6",
    );
  });

  it("REJECTS a bare section number in a data file, which has no comments at all", () => {
    expect(said(violating.phantomSection)).toContain("examples/typescript/violating.json:2  §8.6");
  });

  it("REJECTS a bare head OUTSIDE the book's range instead of dropping it", () => {
    expect(said(violating.phantomSection)).toContain("§99.9");
  });

  it("REJECTS a G-id the registry does not carry", () => {
    expect(said(violating.phantomLaw)).toContain("G17");
  });

  it("REJECTS a check id cited as authority in the book", () => {
    expect(said(violating.bookCid)).toContain("wiki/violating.html:1  C7");
  });
});

describe("the reference lint ALLOWS a compliant corpus", () => {
  const compliant = citationProblems(
    [
      corpusFile("compliant", "code.ts", "examples/typescript/src/compliant.ts"),
      corpusFile("compliant", "prose.md", "examples/typescript/COMPLIANT.md"),
      corpusFile("compliant", "data.json", "examples/typescript/compliant.json"),
    ],
    sections,
    lawIds,
  );

  it("passes every spelling the sweep introduced, and every near-miss", () => {
    // `G9, 14.1`, `§15.4`, `14.1.1`, `12.4`, `6.8`, a roster row naming C4, a
    // `[C2]` message tag, `node >=14.17`, `Apache-2.0` and `2.5.5`.
    expect(said(compliant.retired)).toBe("");
    expect(said(compliant.phantomSection)).toBe("");
    expect(said(compliant.phantomLaw)).toBe("");
    expect(said(compliant.bookCid)).toBe("");
  });
});

// ── THE SECOND COORDINATE — the cross-reference lint's own pair ───────────
//
// The citation lint above judges a reference's TEXT. These judge a LINK: the
// href AND the visible label, which are two claims about one destination and can
// disagree. Both were unguarded — the href by a two-way grep run by hand, the
// label by nothing — and one label was wrong for the whole life of the repo.
//
// The whole of `wiki/` is swept, not the book alone: the worked example's pages
// link up into the book, and a fragment that resolves in one file and not the
// other is the same defect wearing a longer href.

const wikiPages = liveCorpus.filter(
  (file) => file.path.startsWith("wiki/") && file.path.endsWith(".html"),
);
const refs = crossRefProblems(wikiPages);
const located = (hits: readonly { where: string; text: string }[]): string[] =>
  hits.map((h) => `${h.where}  ${h.text}`);

describe("cross-references agree in BOTH coordinates", () => {
  it("SWEPT SOMETHING — an empty anchor list or an empty id map passes everything", () => {
    // The vacuity guard and the anti-deletion pin in one: zeroing any denial
    // below by cutting anchors, or by rewriting an adjudicable label into prose,
    // moves one of these equalities. Inflation is as red as deletion.
    expect(wikiPages.map((f) => f.path)).toEqual([
      "wiki/example/01-state-and-fold.html",
      "wiki/example/02-the-boundary.html",
      "wiki/example/03-tools-and-context.html",
      "wiki/example/04-projection-and-surface.html",
      "wiki/example/05-ports-and-swap.html",
      "wiki/example/06-blocks-and-root.html",
      "wiki/example/07-replay-and-advanced.html",
      "wiki/example/index.html",
      "wiki/index.html",
    ]);
    // 692 -> 693: D42's CHANGELOG landing added one cross-reference to the
    // book, in the diff before this one. The pin moves deliberately with a
    // reason, never loosened to an inequality — that is what makes it a
    // vacuity guard rather than a floor.
    expect(refs.anchors).toBe(693);
    // 18 in the book — the seventeen section ids plus `the-dependency-rule`, the
    // in-section note anchor §7 owns; `nav` sits before the first section and
    // carries no number — plus the worked example's own six (00–05) in
    // `wiki/example/index.html`. The seam pages head their parts ▸/A–E, which
    // are not digits, so their ids resolve to no number.
    expect(refs.numberedTargets).toBe(24);
    // 17 book TOC links carrying a fragment, and 64 whole-file ones — 8 on each
    // of the 8 example pages. The split is the load-bearing half of the nav
    // class: the seam pages' token sets are EMPTY and the worked example's nav
    // runs 00–07 over a page numbered 00–05, so adjudicating a whole-file nav
    // link would manufacture sixty-plus false positives against correct markup.
    expect(refs.labels).toEqual({
      nav: 17,
      navWholeFile: 64,
      // 243 -> 244: the same D42 CHANGELOG cross-reference that moved `anchors`.
      numbered: 244,
      worded: 4,
      law: 49,
      prose: 315,
    });
    // the census is TOTAL: every anchor lands in exactly one bucket.
    expect(Object.values(refs.labels).reduce((a, b) => a + b, 0)).toBe(refs.anchors);
    // Without these three the whole "no section number is a disagreement", the
    // external exemption and the law-definition derivation can go silently
    // inert: `anchors`, `numberedTargets` and `labels` are ALL invariant under a
    // label repointed at a numberless id.
    expect(refs.numberlessTargets).toBe(0);
    expect(refs.external).toBe(0);
    // 16 cells, G1–G16, all in one section (§15's invariant table). The law
    // rule's vacuity guard: a markup change that stopped matching cells would
    // otherwise turn class 5 into a silence rather than a red.
    expect(refs.lawDefinitions).toBe(16);
    expect(refs.lawDefinitionSections).toBe(1);
  });

  it("SECTIONS ARE FLAT — the id→section map's unstated assumption, asserted", () => {
    // `SECTION` splits on a lookahead, so a NESTED `<section>` would attribute
    // every id after the inner open to the inner section's number. Measured true
    // on all nine pages today, and nothing else in the suite would move if it
    // stopped being true.
    expect(refs.maxSectionDepth).toBe(1);
    expect(refs.unbalancedPages).toEqual([]);
  });

  it("PINS THE CROSS-REFERENCE PREDICATES — a weakened denial is a visible diff", () => {
    expect(ANCHOR.source).toBe('<a\\b[^>]*\\bhref="([^"]*)"[^>]*>([\\s\\S]*?)<\\/a>');
    expect(TAGS.source).toBe("<[^>]*>");
    expect(ELEMENT_ID.source).toBe('\\bid="([^"]+)"');
    expect(SECTION.source).toBe("(?=<section\\b)");
    expect(SECTION_TAG.source).toBe("<section\\b|<\\/section\\s*>");
    expect(HEAD.source).toBe('<span class="num">(\\d+)<\\/span>');
    expect(SUBHEAD.source).toBe('<h3><span class="t">([\\d.]+)<\\/span>');
    expect(NAV_LABEL.source).toBe('^\\s*<span class="n">(\\d+)<\\/span>');
    expect(SECTION_SIGN.source).toBe("^§\\s?");
    expect(NUMBER_LABEL.source).toBe("^(\\d{1,2})(?:\\.\\d{1,2}){0,2}$");
    expect(WORDED_LABEL.source).toBe("^sections?\\s+(\\d{1,2})\\b");
    expect(LAW_LABEL.source).toBe("^G\\d+$");
    expect(LAW_CELL.source).toBe("<td[^>]*>\\s*(G\\d+)\\s*<\\/td>");
    expect(EXTERNAL.source).toBe("^(?:[a-z][a-z0-9+.-]*:|\\/\\/)");
    // ONE parser for the book's heads, so `bookSections` and the id→number map
    // cannot drift apart and leave one of them matching nothing.
    expect(bookSections('<span class="num">04</span>')).toEqual(new Set(["04", "4"]));
  });

  it("lands every href on an id that exists", () => {
    expect(located(refs.dangling)).toEqual([]);
  });

  it("labels no link with a section the book does not have", () => {
    expect(located(refs.phantomLabel)).toEqual([]);
  });

  it("labels no link with a number that disagrees with where it lands", () => {
    // Covers all three number spellings — the table-of-contents `<span
    // class="n">`, the bare `14.3`, and the `§01` the sweep mandates in prose.
    expect(located(refs.numberedLabel)).toEqual([]);
  });

  it("labels no link with a WORD FORM that disagrees with where it lands", () => {
    // The one live defect this landing fixed: `wiki/index.html:401` said
    // `section 04` over an href to `#signed-command-bus`, which is §5 — the
    // signed `Command` is introduced at §5.1, so the LABEL was the wrong half
    // and the href was right. Present since the original repo split.
    expect(located(refs.wordedLabel)).toEqual([]);
  });

  it("lands every law label where that law is WRITTEN DOWN", () => {
    expect(located(refs.lawLabel)).toEqual([]);
  });
});

const brokenRefs = crossRefProblems([
  corpusFile("violating", "book.html", "wiki/index.html"),
  corpusFile("violating", "seam.html", "wiki/example/seam.html"),
]);

describe("the cross-reference lint DENIES a violating corpus", () => {
  it("REJECTS an href with no id behind it, IN PAGE", () => {
    expect(said(brokenRefs.dangling)).toContain("wiki/index.html:26  the fourth -> #delta");
  });

  it("REJECTS an href whose PAGE is not in the corpus", () => {
    expect(said(brokenRefs.dangling)).toContain(
      "wiki/index.html:27  a page that is not in the corpus -> example/missing.html#anything",
    );
  });

  it("REJECTS an href that resolves ACROSS FILES onto a fragment that does not", () => {
    expect(said(brokenRefs.dangling)).toContain(
      "wiki/example/seam.html:13  the book -> ../index.html#nope",
    );
  });

  it("REJECTS a NAV label naming a section the book does not have", () => {
    // The book's own table of contents, over a PERFECT href. The number lives in
    // a dedicated element and is fused into the title by any flattening read, so
    // a rule that only saw the flattened label scored `09Second` as prose.
    expect(said(brokenRefs.phantomLabel)).toContain("wiki/index.html:15  09Second -> #beta");
  });

  it("REJECTS a NAV label that disagrees with where it lands", () => {
    expect(said(brokenRefs.numberedLabel)).toContain(
      "wiki/index.html:14  02Third -> #gamma (= section 3)",
    );
  });

  it("REJECTS a bare label naming a section the book does not have, over a GOOD href", () => {
    expect(said(brokenRefs.phantomLabel)).toContain("wiki/index.html:21  9.9 -> #alpha");
  });

  it("REJECTS the same phantom in the §-MARKED spelling the sweep mandates", () => {
    expect(said(brokenRefs.phantomLabel)).toContain("wiki/index.html:23  §9.9 -> #alpha");
  });

  it("REJECTS a NUMBERED label that disagrees with where it lands", () => {
    expect(said(brokenRefs.numberedLabel)).toContain(
      "wiki/index.html:49  2.1 -> #gamma (= section 3)",
    );
  });

  it("REJECTS the same disagreement in the §-MARKED spelling", () => {
    expect(said(brokenRefs.numberedLabel)).toContain(
      "wiki/index.html:49  §02 -> #gamma (= section 3)",
    );
  });

  it("REJECTS a WORD-FORM label that disagrees with where it lands", () => {
    // The class the live defect was in. Building only the bare-number half would
    // have shipped a checker that was green before and after.
    expect(said(brokenRefs.wordedLabel)).toContain(
      "wiki/index.html:50  section 02 -> #gamma (= section 3)",
    );
  });

  it("REJECTS a NUMBER landing on an id that sits in NO section", () => {
    // Not an exemption. The label names a book section; the table of contents is
    // not one. Every guard that read `section !== null` was inert here.
    expect(said(brokenRefs.numberedLabel)).toContain(
      "wiki/index.html:54  01 -> #nav (= no section)",
    );
  });

  it("REJECTS a WORD FORM landing on an id that sits in NO section", () => {
    expect(said(brokenRefs.wordedLabel)).toContain(
      "wiki/index.html:55  section 01 -> #nav (= no section)",
    );
  });

  it("REJECTS a number landing on a LETTERED part, the live seam idiom", () => {
    // The seam pages head their parts `▸`/`A`–`E`. The page's token set is not
    // empty — it has a numbered part too — so this is a numberless TARGET rather
    // than a phantom, which is the branch a page-level guard cannot reach.
    expect(said(brokenRefs.numberedLabel)).toContain(
      "wiki/index.html:56  01 -> example/seam.html#part-a (= no section)",
    );
  });

  it("REJECTS a law label landing where that law is NOT written down", () => {
    expect(said(brokenRefs.lawLabel)).toContain("wiki/index.html:31  G4 -> #alpha");
  });

  it("REJECTS a law label landing where the law is only MENTIONED — the sieve", () => {
    // The weakest possible spelling of class 5 asks whether the destination's
    // text carries the id. §2 of the fixture carries `G4` in prose and defines
    // it nowhere; measured on the live book, every G-id has at least two such
    // carriers, so under a mention rule all 49 live law labels were repointable
    // and green. The rule reads the DEFINITION CELL.
    expect(said(brokenRefs.lawLabel)).toContain("wiki/index.html:39  G4 -> #beta");
  });

  it("and is not silent because it read nothing", () => {
    expect(brokenRefs.anchors).toBe(17);
    expect(brokenRefs.labels).toEqual({
      nav: 3,
      navWholeFile: 0,
      numbered: 6,
      worded: 2,
      law: 2,
      prose: 4,
    });
    expect(brokenRefs.numberedTargets).toBe(5);
    expect(brokenRefs.numberlessTargets).toBe(3);
    expect(brokenRefs.lawDefinitions).toBe(1);
  });
});

describe("the cross-reference lint ALLOWS a compliant corpus", () => {
  const cleanRefs = crossRefProblems([
    corpusFile("compliant", "book.html", "wiki/index.html"),
    corpusFile("compliant", "seam.html", "wiki/example/seam.html"),
  ]);

  it("passes every agreeing spelling, and every near-miss", () => {
    // Padded and unpadded heads, a `§02` that agrees, a subsection label, a
    // plural word form, a law label asserted from outside the section whose cell
    // defines it, a numeric label pointing at an IN-SECTION anchor, an agreeing
    // nav link, a WHOLE-FILE nav link, a cross-file page-and-fragment, three
    // outbound hrefs (`https:`, `mailto:`, protocol-relative), and the prose
    // labels — a law RANGE, a figure, a sentence, a bare `§ mapping`, a page
    // name — none of which a machine may adjudicate.
    expect(said(cleanRefs.dangling)).toBe("");
    expect(said(cleanRefs.phantomLabel)).toBe("");
    expect(said(cleanRefs.numberedLabel)).toBe("");
    expect(said(cleanRefs.wordedLabel)).toBe("");
    expect(said(cleanRefs.lawLabel)).toBe("");
  });

  it("and is not silent because it read nothing", () => {
    // The allow half's own vacuity guard: a compliant fixture that stopped
    // carrying adjudicable labels would pass for the wrong reason. `external: 3`
    // is the false-positive proof — three hrefs that name no corpus page and are
    // counted rather than spliced through the relative-path resolver.
    expect(cleanRefs.anchors).toBe(23);
    expect(cleanRefs.labels).toEqual({
      nav: 3,
      navWholeFile: 2,
      numbered: 6,
      worded: 2,
      law: 1,
      prose: 9,
    });
    expect(cleanRefs.numberedTargets).toBe(4);
    expect(cleanRefs.numberlessTargets).toBe(0);
    expect(cleanRefs.external).toBe(3);
    expect(cleanRefs.lawDefinitions).toBe(1);
    expect(cleanRefs.maxSectionDepth).toBe(1);
  });
});
